language: cpp

compiler:
    - gcc
    - clang

script:
    - make -f build/system-setup/make-system install-packages
    - make -f build/system-setup/make-system install-dependencies
    - mkdir build/build && cd build/build
    - cmake ..
    - make
