language: cpp

compiler:
    - gcc
    - clang

script:
    - make -f ci/make-system install-packages
    - make -f ci/make-system install-dependencies
    - mkdir build && cd build
    - cmake ..
    - make
